name : PMD

on :
  push:
  pull_request:

permissions:
  contents: read

jobs:
  PMD_test:
    name: Run PMD Tests
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - uses: pmd/pmd-github-action@v1
        id: pmd
        with:
          version: '7.0.0-rc4'
          sourcePath: 'src/'
          rulesets: 'rulesets/java/quickstart.xml,ruleset.xml'
          analyzeModifiedFilesOnly: 'false'
          format: 'text'
          failOnViolation: true
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-report.sarif
